---
- hosts: all
  sudo: yes
  gather_facts: yes
  remote_user: vagrant
  
  vars:
    user: vagrant
  tasks:

  - name: Configure hosts file
    lineinfile:
      regexp: "{{item}}"
      line: "{{hostvars[item]['ansible_eth1']['ipv4']['address']}} {{item}}"
      dest: /etc/hosts
    with_items: groups['all']

  - name: copy ssh public key
    authorized_key: user={{user}} key="{{ lookup('file', '/home/{{user}}/.ssh/id_rsa.pub')}}"

  - name: upgrade all packages
    yum: name=* state=latest
  
  - name: Disable firewalld
    service:
      name: firewalld
      state: stopped
      enabled: no
  
  - name: Upgrade to  CentOS 7.2
    shell: yum upgrade --assumeyes --tolerant && sudo yum update --assumeyes

  - name: Enable OverlayFS
    template: 
          src: templates/overlay.conf.j2
          dest: /etc/modules-load.d/overlay.conf

  - name: Configure yum to use the Docker yum repo
    template:
         src: templates/docker.repo.j2
         dest: /etc/yum.repos.d/docker.repo
  
  - name: create docker service directory
    file: path=/etc/systemd/system/docker.service.d state=directory
  
  - name: Configure systemd to run the Docker Daemon with OverlayFS
    template:
        src: templates/override.conf.j2
        dest: /etc/systemd/system/docker.service.d/override.conf

  - name: intall docker
    yum: 
       name: docker-engine
       state: present
    
  - name: Enable docker
    service:
      name: docker
      state: started
      enabled: yes
  
  - name: Install Utilities
    yum: name={{item}} state=present
    with_items:
        - tar
        - xz 
        - unzip 
        - curl 
        - ipset
   
- hosts: bootstrap
  sudo: yes
  gather_facts: yes
  remote_user: vagrant

  tasks:
  
  - name: install HAProxy
    yum:
       name: haproxy
       state: present
  
